/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class veterinarian extends javax.swing.JFrame {

    /**
     * Creates new form Veterinario
     */
    public veterinarian() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buttonprocedure = new javax.swing.JButton();
        Buttonsurgeries = new javax.swing.JButton();
        Buttonappoinment = new javax.swing.JButton();
        textwelcom = new javax.swing.JLabel();
        labelnameveterinarian = new javax.swing.JLabel();
        ButtonAddDiagnosis = new javax.swing.JButton();
        ButtonClosedSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        Buttonprocedure.setBackground(new java.awt.Color(204, 255, 204));
        Buttonprocedure.setText("Ver Procedimientos Realizados");
        Buttonprocedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonprocedureActionPerformed(evt);
            }
        });

        Buttonsurgeries.setBackground(new java.awt.Color(204, 255, 204));
        Buttonsurgeries.setText("Ver Cirujias Realizadas");

        Buttonappoinment.setBackground(new java.awt.Color(204, 255, 204));
        Buttonappoinment.setText("Consultas Realizadas");

        textwelcom.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textwelcom.setForeground(new java.awt.Color(255, 255, 255));
        textwelcom.setText("      BIENVENIDO");

        labelnameveterinarian.setForeground(new java.awt.Color(255, 255, 255));
        labelnameveterinarian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnameveterinarian.setText("Nombre Veterinario");

        ButtonAddDiagnosis.setBackground(new java.awt.Color(204, 255, 204));
        ButtonAddDiagnosis.setText("Realizar diagnostico");
        ButtonAddDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddDiagnosisActionPerformed(evt);
            }
        });

        ButtonClosedSesion.setBackground(new java.awt.Color(204, 255, 204));
        ButtonClosedSesion.setText("Cerrar sesion");
        ButtonClosedSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClosedSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelnameveterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textwelcom, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonClosedSesion)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonAddDiagnosis, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Buttonappoinment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Buttonsurgeries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Buttonprocedure, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                        .addGap(84, 84, 84))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(textwelcom)
                .addGap(18, 18, 18)
                .addComponent(labelnameveterinarian)
                .addGap(18, 18, 18)
                .addComponent(Buttonprocedure)
                .addGap(18, 18, 18)
                .addComponent(Buttonsurgeries)
                .addGap(18, 18, 18)
                .addComponent(Buttonappoinment)
                .addGap(18, 18, 18)
                .addComponent(ButtonAddDiagnosis)
                .addGap(43, 43, 43)
                .addComponent(ButtonClosedSesion)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonprocedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonprocedureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonprocedureActionPerformed

    private void ButtonAddDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddDiagnosisActionPerformed

    private void ButtonClosedSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClosedSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonClosedSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new veterinarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonAddDiagnosis;
    public javax.swing.JButton ButtonClosedSesion;
    public javax.swing.JButton Buttonappoinment;
    public javax.swing.JButton Buttonprocedure;
    public javax.swing.JButton Buttonsurgeries;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelnameveterinarian;
    public javax.swing.JLabel textwelcom;
    // End of variables declaration//GEN-END:variables
}
