/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class veterinarian extends javax.swing.JFrame {

    /**
     * Creates new form Veterinario
     */
    public veterinarian() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buttonprocedure = new javax.swing.JButton();
        Buttonsurgeries = new javax.swing.JButton();
        Buttonappoinment = new javax.swing.JButton();
        Buttonback = new javax.swing.JButton();
        textwelcom = new javax.swing.JLabel();
        labelnameveterinarian = new javax.swing.JLabel();
        ButtonAddDiagnosis = new javax.swing.JButton();
        ButtonAddSurgeries = new javax.swing.JButton();
        ButtonADDSurgeries = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        Buttonprocedure.setBackground(new java.awt.Color(204, 255, 204));
        Buttonprocedure.setText("Ver Procedimientos Realizados");
        Buttonprocedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonprocedureActionPerformed(evt);
            }
        });

        Buttonsurgeries.setBackground(new java.awt.Color(204, 255, 204));
        Buttonsurgeries.setText("Ver Cirujias Realizadas");

        Buttonappoinment.setBackground(new java.awt.Color(204, 255, 204));
        Buttonappoinment.setText("Consultas Realizadas");

        Buttonback.setBackground(new java.awt.Color(204, 255, 204));
        Buttonback.setText("Volver");

        textwelcom.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textwelcom.setForeground(new java.awt.Color(255, 255, 255));
        textwelcom.setText("      BIENVENIDO");

        labelnameveterinarian.setForeground(new java.awt.Color(255, 255, 255));
        labelnameveterinarian.setText("Nombre Veterinario");

        ButtonAddDiagnosis.setBackground(new java.awt.Color(204, 255, 204));
        ButtonAddDiagnosis.setText("Realizar diagnostico");
        ButtonAddDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddDiagnosisActionPerformed(evt);
            }
        });

        ButtonAddSurgeries.setBackground(new java.awt.Color(204, 255, 204));
        ButtonAddSurgeries.setText("Enviar Cirujia");
        ButtonAddSurgeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddSurgeriesActionPerformed(evt);
            }
        });

        ButtonADDSurgeries.setBackground(new java.awt.Color(204, 255, 204));
        ButtonADDSurgeries.setText("Enviar Procedimiento");
        ButtonADDSurgeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonADDSurgeriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(textwelcom, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(Buttonback))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buttonsurgeries, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonprocedure)
                            .addComponent(Buttonappoinment, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonAddDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonAddSurgeries, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonADDSurgeries, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelnameveterinarian)
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textwelcom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelnameveterinarian)
                .addGap(24, 24, 24)
                .addComponent(Buttonprocedure)
                .addGap(26, 26, 26)
                .addComponent(Buttonsurgeries)
                .addGap(18, 18, 18)
                .addComponent(Buttonappoinment)
                .addGap(18, 18, 18)
                .addComponent(ButtonAddDiagnosis)
                .addGap(26, 26, 26)
                .addComponent(ButtonAddSurgeries)
                .addGap(26, 26, 26)
                .addComponent(ButtonADDSurgeries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Buttonback)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonprocedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonprocedureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonprocedureActionPerformed

    private void ButtonAddDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddDiagnosisActionPerformed

    private void ButtonAddSurgeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddSurgeriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddSurgeriesActionPerformed

    private void ButtonADDSurgeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonADDSurgeriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonADDSurgeriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(veterinarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new veterinarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonADDSurgeries;
    private javax.swing.JButton ButtonAddDiagnosis;
    private javax.swing.JButton ButtonAddSurgeries;
    public javax.swing.JButton Buttonappoinment;
    public javax.swing.JButton Buttonback;
    public javax.swing.JButton Buttonprocedure;
    public javax.swing.JButton Buttonsurgeries;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelnameveterinarian;
    public javax.swing.JLabel textwelcom;
    // End of variables declaration//GEN-END:variables
}
