/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class ViewProcedures extends javax.swing.JFrame {

    /**
     * Creates new form ViewProcedures
     */
    public ViewProcedures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Paneltitle = new javax.swing.JPanel();
        labelprocedures = new javax.swing.JLabel();
        Buttonbackprocedures = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableviewprocedure = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Paneltitle.setBackground(new java.awt.Color(0, 102, 51));
        Paneltitle.setForeground(new java.awt.Color(255, 255, 255));

        labelprocedures.setBackground(new java.awt.Color(255, 255, 255));
        labelprocedures.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelprocedures.setForeground(new java.awt.Color(255, 255, 255));
        labelprocedures.setText("  PROCEDIMIENTOS REALIZADOS");

        Buttonbackprocedures.setBackground(new java.awt.Color(204, 255, 204));
        Buttonbackprocedures.setText("Volver");

        tableviewprocedure.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_Mascota", "procedimiento", "fecha", "ID cita"
            }
        ));
        jScrollPane1.setViewportView(tableviewprocedure);

        javax.swing.GroupLayout PaneltitleLayout = new javax.swing.GroupLayout(Paneltitle);
        Paneltitle.setLayout(PaneltitleLayout);
        PaneltitleLayout.setHorizontalGroup(
            PaneltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneltitleLayout.createSequentialGroup()
                .addGroup(PaneltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneltitleLayout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(Buttonbackprocedures))
                    .addGroup(PaneltitleLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaneltitleLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(labelprocedures)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        PaneltitleLayout.setVerticalGroup(
            PaneltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneltitleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelprocedures)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Buttonbackprocedures)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paneltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Paneltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProcedures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProcedures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProcedures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProcedures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProcedures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Buttonbackprocedures;
    private javax.swing.JPanel Paneltitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelprocedures;
    public javax.swing.JTable tableviewprocedure;
    // End of variables declaration//GEN-END:variables
}
